run:
  timeout: 10m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # disable some excludes that golangci-lint has by default. see https://github.com/golangci/golangci-lint
  exclude-use-default: false
  exclude-rules:
      # This project does not have a rule to avoid unkeyed fields
      - linters:
          - govet
        text: composite literal uses unkeyed fields
      # Disable duplicate code, constant strings, unused params validation in testing
      - path: _test\.go$
        linters:
          - goconst
          - unparam
      # These checks are not really useful
      - linters:
          - errcheck
        text: "Error return value of `.*(Close|Remove)` is not checked"
      # This project does not have a rule to have a doc comment for all packages
      - linters:
          - stylecheck
        text: "at least one file in a package should have a package comment"

linters:
  enable-all: true
  disable:
    # This project does not have a rule to have no globals
    - gochecknoglobals
    # This project does not have a rule to have no inits
    - gochecknoinits
    # This test has too many false positives
    - gocyclo
    # This project does not have a standard line length
    - lll
    # This project does not care about optimizing out few bytes of memory
    - maligned
    # These checks are of a very low quality
    - gosec
    # This linter finds duplicate code where it is plain old Go repetiveness
    - dupl
    # This project explicitly allows FIXMEs in the code
    - godox
    # This project does not have a rule to limit the length of functions
    - funlen
    # This check is stupid
    - wsl
    # This check is too simplistic, marks even simple functions as "cognitively complex"
    - gocognit
    # This check has too many false positives
    - bodyclose
    # This check has good indentions but floods with false positives
    - gomnd
    # This check has too many false positives
    - interfacer

linters-settings:
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 1
