branches:
  only:
  - master

language: go
cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod
go:
- tip
- 1.15.x # see version in Makefile:check-go-mod
- 1.14.x
- 1.13.x
install: true
script:
- make check
